#!/bin/sh
#PBS -N MD
#PBS -q full
#PBS -l select=1:ncpus=4:ngpus=1

module load lammps/intel/oneapi/mace
cd $PBS_O_WORKDIR
source /home/junho/anaconda3/etc/profile.d/conda.sh
conda activate mace_cuda

python run.py
